
Insert into tblAppSettings(PropertyName,PropertyValue)Values('CurrentClientID',0)

GO
-- drop table tblClientInfo
Create table tblClientInfo(
ClientID nvarchar(50) primary key,
ClientName nvarchar(200),
ContactNumber nvarchar(50),
PresentAddress nvarchar(500),
PermanentAddress nvarchar(500),
EntryBy nvarchar(50),
EntryDate datetime default getdate()
);

Select ClientID from tblClientInfo Where ClientID >'C-00000303'

GO

Create proc spInsertClientInfo
@ClientName nvarchar(200),
@ContactNumber nvarchar(50),
@PresentAddress nvarchar(500),
@PermanentAddress nvarchar(500),
@EntryBy nvarchar(50)
as
begin
	Declare @ClientID nvarchar(50)
	Declare @CurrentClientID numeric(18,0)
	Declare @ClientIDPrefix as nvarchar(2)

	set @ClientIDPrefix='C-'

begin tran
	
	select @CurrentClientID = cast(PropertyValue as numeric(18,0)) from tblAppSettings where  PropertyName='CurrentClientID'
	
	set @CurrentClientID=isnull(@CurrentClientID,0)+1
	Select @ClientID=dbo.generateID(@ClientIDPrefix,@CurrentClientID,8)		
	IF (@@ERROR <> 0) GOTO ERR_HANDLER

	Insert into tblClientInfo(ClientID,ClientName,ContactNumber,PresentAddress,PermanentAddress,EntryBy)
	Values(@ClientID,@ClientName,@ContactNumber,@PresentAddress,@PermanentAddress,@EntryBy)
	IF (@@ERROR <> 0) GOTO ERR_HANDLER

	update tblAppSettings set PropertyValue=@CurrentClientID where PropertyName='CurrentClientID'
	IF (@@ERROR <> 0) GOTO ERR_HANDLER

COMMIT TRAN
RETURN 0
ERR_HANDLER:
ROLLBACK TRAN
RETURN 1
end

GO

Select ClientID from tblClientInfo order by ClientName

GO

/* DF Client ***
exec spInsertClientInfo 'A. B. ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'ADITI ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'ALAUL ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'AL-BARAKA MOTORS','','','','dsamaddar'
exec spInsertClientInfo 'ASSOCIATE TRADING','','','','dsamaddar'
exec spInsertClientInfo 'AYSHA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'BISMILLAH AUTO MOBILE AND FOODS','','','','dsamaddar'
exec spInsertClientInfo 'BISMILLAH ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'BISMILLAH STORE','','','','dsamaddar'
exec spInsertClientInfo 'BROTHER'S CORPORATION','','','','dsamaddar'
exec spInsertClientInfo 'CHANDRA BINDU','','','','dsamaddar'
exec spInsertClientInfo 'CHUMKI ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'DIAMOND CYCLE STORE','','','','dsamaddar'
exec spInsertClientInfo 'ETTADI GENERAL STORE','','','','dsamaddar'
exec spInsertClientInfo 'FOUR STAR ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'GREEN BANGLADESH LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'GREEN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'H B ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'H P DISTRIBUTION','','','','dsamaddar'
exec spInsertClientInfo 'HAZI ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'HIMEL COSMATICS','','','','dsamaddar'
exec spInsertClientInfo 'HOSSAIN FAST FOOD AND DEPARTMENTAL STORE','','','','dsamaddar'
exec spInsertClientInfo 'I. W. DISTRIBUTION','','','','dsamaddar'
exec spInsertClientInfo 'IDEAL COMMUNICATIONS','','','','dsamaddar'
exec spInsertClientInfo 'IKRA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'J. R. TRADING CO.','','','','dsamaddar'
exec spInsertClientInfo 'J.K. ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'KAFIL & BROTHERS','','','','dsamaddar'
exec spInsertClientInfo 'KHAN & BROTHERS','','','','dsamaddar'
exec spInsertClientInfo 'KHAN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'KIRON STORE','','','','dsamaddar'
exec spInsertClientInfo 'KOLLAYANI ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'LITON KUMAR DEY','','','','dsamaddar'
exec spInsertClientInfo 'M/S A LATIF ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S A P ENTERPRIZE','','','','dsamaddar'
exec spInsertClientInfo 'M/S ABDULLAH AND BROTHERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S ABID STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S AKIL TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S AL AMIN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S AL AMIN FILLING STATION','','','','dsamaddar'
exec spInsertClientInfo 'M/S AL MADINA STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S ALA UDDIN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S ALAMGIR & BROTHERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S AMANAT ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S ANAMIKA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S ANISA TRADING','','','','dsamaddar'
exec spInsertClientInfo 'M/S ASHA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S ASIF & BROTHERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S ASRAF TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S BABUL STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S BABUL TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S BABY ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S BANANI ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S BAPPY STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S BARAITALI FISHERIES','','','','dsamaddar'
exec spInsertClientInfo 'M/S BARKAT & GENERAL STORES','','','','dsamaddar'
exec spInsertClientInfo 'M/S BELAL SALES AND DISTRIBUTION','','','','dsamaddar'
exec spInsertClientInfo 'M/S BHANDER OIL AGENCY','','','','dsamaddar'
exec spInsertClientInfo 'M/S BIDDUTH COSMETICS','','','','dsamaddar'
exec spInsertClientInfo 'M/S BISMILLAH POULTRY FEEDS & CHICKS','','','','dsamaddar'
exec spInsertClientInfo 'M/S BLESS ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S CHOWDHURY ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S CHULA GHAR','','','','dsamaddar'
exec spInsertClientInfo 'M/S DIDAR ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S EKOSHA EENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S FIROZA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S HAJI SULTAN STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S HAZI SHAWKAT TRADE INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'M/S HOQUE ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S HUMAYERA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S HUMAYUN STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S ISHAQUE TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S JABED ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S JASHIM ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S JEWEL TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S JOARDDER ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S K. C. ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S K. S. TRADING','','','','dsamaddar'
exec spInsertClientInfo 'M/S K.S. RAHMAN & CO.','','','','dsamaddar'
exec spInsertClientInfo 'M/S KHANDAKAR TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S KHONDOKAR FUEL AGENCY','','','','dsamaddar'
exec spInsertClientInfo 'M/S KOHINOOR ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S LAKI STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S M ALI TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S M M TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S M.S. ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S MAISHA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S MAMUN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S MARKUP SALES AND DISTRIBUTION','','','','dsamaddar'
exec spInsertClientInfo 'M/S MD. SHAHAB UDDIN STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S MITRA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S MODINA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S MOHAMMADIA DISTRIBUTION','','','','dsamaddar'
exec spInsertClientInfo 'M/S MOJIBAR STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S MONI ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S MUBIN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S MUSA STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S N ALAM TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S NABARUN STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S NABILA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S NAHAR ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S NASIR TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S NAZNIN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S NEW G. PAUL DISTRIBUTION','','','','dsamaddar'
exec spInsertClientInfo 'M/S NEW RAMPURA RICE','','','','dsamaddar'
exec spInsertClientInfo 'M/S NURJAHAN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S PALASH ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S PAPAI INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'M/S PRANTIK FILLING STATION','','','','dsamaddar'
exec spInsertClientInfo 'M/S PROGOTI ELECTRIC AND ELECTRONICS','','','','dsamaddar'
exec spInsertClientInfo 'M/S RAHI ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S RATUL ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S RAWSHAN FILLING STATION','','','','dsamaddar'
exec spInsertClientInfo 'M/S REDWAN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S RUPALI ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S S. B. ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S S. K TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S S.S. CORPORATION','','','','dsamaddar'
exec spInsertClientInfo 'M/S S.S. TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S SAAD ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S SALAUDDIN STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S SAMI TRADING','','','','dsamaddar'
exec spInsertClientInfo 'M/S SANJIB ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S SAON STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S SARDER VARIETY STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S SATATA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S SATATA POULTRY FEED','','','','dsamaddar'
exec spInsertClientInfo 'M/S SATATA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S SATHI ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S SAZZAD ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S SEBA STATIONARY','','','','dsamaddar'
exec spInsertClientInfo 'M/S SHABAN BAJAJ','','','','dsamaddar'
exec spInsertClientInfo 'M/S SHAH AMANAT TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S SHAHADAT HOSSAIN','','','','dsamaddar'
exec spInsertClientInfo 'M/S SHAHAJADA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S SHAON ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S SHARANIKA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S SHIPU ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S SHITAL TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S SIKDER ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S SIM TEL','','','','dsamaddar'
exec spInsertClientInfo 'M/S SK. A TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S SOTOTA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S SUMAIYA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S TAHER ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S TAHER TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S TANVIR ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S TAUHID ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S TORIQUL ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S TOWHID ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S TRISHNA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S TULIP INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'M/S UTTARA MILLS','','','','dsamaddar'
exec spInsertClientInfo 'M/S ZAMAN TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S ZAMAN TRADING','','','','dsamaddar'
exec spInsertClientInfo 'M/S. A. RAHIM TRADING & AGRO BUSINESS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ABDUL HAI','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ABDUL MAZID MIAH & SONS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ABUL LAIS & SONS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ADIL ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. AHMED TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. AL ARAFAH FILLING STATION','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ALAL POULTRY FEED','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ALAMPUR ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ANTORA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ASAB BROTHERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ASAD ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. AUTO BITAN','','','','dsamaddar'
exec spInsertClientInfo 'M/S. AZIZ BROTHERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. BANIJJA BITAN','','','','dsamaddar'
exec spInsertClientInfo 'M/S. BHAI BHAI MINI AUTO CHAUL KAL','','','','dsamaddar'
exec spInsertClientInfo 'M/S. BORNALI TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. COX'S BAZAR TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. DOST TRADERS FILLING STATION','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ELMA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ERSHAD TRADING','','','','dsamaddar'
exec spInsertClientInfo 'M/S. FARUK STORES','','','','dsamaddar'
exec spInsertClientInfo 'M/S. FERDOUS TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. GIAS ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. GREENLAND ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. HASIB ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. HAZERA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. HAZI TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. HEMEL TRADING','','','','dsamaddar'
exec spInsertClientInfo 'M/S. HILL VIEW','','','','dsamaddar'
exec spInsertClientInfo 'M/S. HOWLADER ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. HRIDITA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. IQBAL TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. J. B. TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. JAHANARA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. K.B. ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. KABIR ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. KALAM AND SONS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. KAMRUNNESSA & SONS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. KEKA FILLING STATION','','','','dsamaddar'
exec spInsertClientInfo 'M/S. KHATUN STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. KHONDOKER ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. KP TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. LOVELY HOUSE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. LUVA MARKETING','','','','dsamaddar'
exec spInsertClientInfo 'M/S. M. A. KHALEQUE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. M.M. FILLING STATION','','','','dsamaddar'
exec spInsertClientInfo 'M/S. MAA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. MAHABUB & BROTHERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. MAMUN CYCLE & MACHINARY','','','','dsamaddar'
exec spInsertClientInfo 'M/S. MAMUN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. MARUFA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. MEHEDI ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. MIM DEPARTMENTAL STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. MOHAMMADIA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. MOULY TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. MUJIBUR RAHAMAN & SONS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. NASIR AND CO.','','','','dsamaddar'
exec spInsertClientInfo 'M/S. NASIR AND CO.','','','','dsamaddar'
exec spInsertClientInfo 'M/S. NASIR ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. NIPA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. NOWRIN TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. PAIRA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. PAUL STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. PROVAT ENTERPRISE & DISTRIBUTION','','','','dsamaddar'
exec spInsertClientInfo 'M/S. RAFIA VARITIS STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. RAHIM POULTRY','','','','dsamaddar'
exec spInsertClientInfo 'M/S. RAJESHWARI ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. RANGPUR FILLING STATION','','','','dsamaddar'
exec spInsertClientInfo 'M/S. RASHED ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. REDWAN TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. RUBEL BROTHERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. S.S ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. S.S. TRADING','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SADESH TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SAIFUDDIN & BROTHERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SAJAL ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SAJIB TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SALAM TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SALMA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SANGIDA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SHAH ENTERPRISE-2','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SHAHJAHAN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SHARIF COSMETICS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SHATHI ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SHEIKH & BROTHERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SHERPUR BAJAJ CENTRE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SHITAL STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SIFAT ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SIM COM','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SULTAN TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SWAPON ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SWARANIKA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. TAYEBIA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. TUSHAR STORE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. UNITED TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. USHA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. YAMIN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ZAMAN TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S.P.K.STORE','','','','dsamaddar'
exec spInsertClientInfo 'MAA MEDICINE & DEPARTMENTAL STORE','','','','dsamaddar'
exec spInsertClientInfo 'MAXTEL','','','','dsamaddar'
exec spInsertClientInfo 'MILENIUM TRADING CORPORATION','','','','dsamaddar'
exec spInsertClientInfo 'MINTU STORE','','','','dsamaddar'
exec spInsertClientInfo 'MIR ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'MOHON TELECOM & VARIETIES STORE','','','','dsamaddar'
exec spInsertClientInfo 'MOON AND BROTHERS','','','','dsamaddar'
exec spInsertClientInfo 'MOTALAB STORE','','','','dsamaddar'
exec spInsertClientInfo 'MOULANA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'MRITTIKA TRADING','','','','dsamaddar'
exec spInsertClientInfo 'MUKTI TRADING','','','','dsamaddar'
exec spInsertClientInfo 'N.S CORPORATION','','','','dsamaddar'
exec spInsertClientInfo 'NAHAR COMMERCIAL','','','','dsamaddar'
exec spInsertClientInfo 'NEW BROTHERS TRADE CENTER','','','','dsamaddar'
exec spInsertClientInfo 'NORTH GROUP','','','','dsamaddar'
exec spInsertClientInfo 'NURJAHAN TRADING','','','','dsamaddar'
exec spInsertClientInfo 'PADMA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'PRATIVA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'PRIYA STORES','','','','dsamaddar'
exec spInsertClientInfo 'PROFESSORS ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'PURNO IRON STORE','','','','dsamaddar'
exec spInsertClientInfo 'RASHID TELECOM','','','','dsamaddar'
exec spInsertClientInfo 'RUBAL MOTORS','','','','dsamaddar'
exec spInsertClientInfo 'RUCHI CONFECTIONARY','','','','dsamaddar'
exec spInsertClientInfo 'S R DISTRIBUTION & CO','','','','dsamaddar'
exec spInsertClientInfo 'S.E ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'S.H. POULTRY FARM & FEED','','','','dsamaddar'
exec spInsertClientInfo 'SAIFULLAH KRISHI AND MOTSHO BIPONI','','','','dsamaddar'
exec spInsertClientInfo 'SAIKAT MOTORS','','','','dsamaddar'
exec spInsertClientInfo 'SALEHEA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'SARDER ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'SARKAR BUSINESS POINT','','','','dsamaddar'
exec spInsertClientInfo 'SATATA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'SHAHZADI TRADING','','','','dsamaddar'
exec spInsertClientInfo 'SHAILY ASSOCIATE','','','','dsamaddar'
exec spInsertClientInfo 'SHEF TRADE CO','','','','dsamaddar'
exec spInsertClientInfo 'SHOAIB ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'SOJIB ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'SONAR BANGLA TRADE INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'SRABON GIFT CORNAR','','','','dsamaddar'
exec spInsertClientInfo 'TAIYABIYA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'TANGAIL MOTORS','','','','dsamaddar'
exec spInsertClientInfo 'TARAPADA SHAHA','','','','dsamaddar'
exec spInsertClientInfo 'TASFIK TRADE INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'TRADE LINK PROMOTION AND DISTRIBUTION','','','','dsamaddar'
exec spInsertClientInfo 'TUHIN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'UDAYON BROTHERS','','','','dsamaddar'
exec spInsertClientInfo 'ZHALAK COMPUTER SOLUTION','','','','dsamaddar'

*/

GO

/* CSF Client ***********
exec spInsertClientInfo 'MECCA MULTILAYER LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'NEETOL','','','','dsamaddar'
exec spInsertClientInfo 'PLATINUM PRINT & PACK LTD.','','','','dsamaddar'
exec spInsertClientInfo 'N RAHMAN ASSOCIATES','','','','dsamaddar'
exec spInsertClientInfo 'PACKSTONE LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'M/S. A. M. PACKAGING','','','','dsamaddar'
exec spInsertClientInfo 'A.R. PLASTIC INDUSTRIES','','','','dsamaddar'
exec spInsertClientInfo 'RAFIQUE TIN CONTAINERS LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'FRIENDS TRADING INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'RAFIQ TRADE INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'MPS PACKAGING LTD.','','','','dsamaddar'
exec spInsertClientInfo 'QUALITY CAN INDUSTRIES LTD.','','','','dsamaddar'
exec spInsertClientInfo 'M/S. BANDHU TRANSPORT AGENCY','','','','dsamaddar'
exec spInsertClientInfo 'CHISTIA PRINTING & PACKAGING LTD.','','','','dsamaddar'
exec spInsertClientInfo 'FARUK PRINTING AND PACKAGING INDUSTRIES','','','','dsamaddar'
exec spInsertClientInfo 'M/S. KHAN PRINTING & PACKAGING','','','','dsamaddar'
exec spInsertClientInfo 'CROWN INK','','','','dsamaddar'
exec spInsertClientInfo 'FM PLASTIC INDUSTRIES','','','','dsamaddar'
exec spInsertClientInfo 'SIDDIQUE PRINTERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SULTANA TRANSPORT','','','','dsamaddar'
exec spInsertClientInfo 'PANNA DISTRIBUTION LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'F M TRADING','','','','dsamaddar'
exec spInsertClientInfo 'AL-MOSTAFA PRINTING & PACKAGING INDUSTRIES LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'BISMILLAH PLASTICS','','','','dsamaddar'
exec spInsertClientInfo 'FRIENDS PRINT AND PACKAGING CO.','','','','dsamaddar'
exec spInsertClientInfo 'JAHANARA CORPORATION','','','','dsamaddar'
exec spInsertClientInfo 'M/S RAISA FRUITS AGENCY','','','','dsamaddar'
exec spInsertClientInfo 'M/S. KHAN IRON','','','','dsamaddar'
exec spInsertClientInfo 'MOLLAH TRADE INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'PROGRESSIVE TRADING CONCERN','','','','dsamaddar'
exec spInsertClientInfo 'SKY BOX','','','','dsamaddar'
exec spInsertClientInfo 'STAR PRINTING & PACKAGING','','','','dsamaddar'
exec spInsertClientInfo 'M/S. OLI TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ALAL ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'JALAL TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S MOON CHAUL KAL','','','','dsamaddar'
exec spInsertClientInfo 'A. B. TRADE INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SHINU TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'BSRM STEELS LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'BANGLADESH STEEL RE-ROLLING MILLS LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'I.S. METAL WORKS','','','','dsamaddar'
exec spInsertClientInfo 'M/S SHYAMOLI TRANSPORT AGENCY','','','','dsamaddar'
exec spInsertClientInfo 'SHAJINAZ EXIM PACK LTD.','','','','dsamaddar'
exec spInsertClientInfo 'M. D. BROTHERS (PVT.) LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'HOSSAIN BOX INDUSTRIES','','','','dsamaddar'
exec spInsertClientInfo 'UNIMIX READYMIX CONCRETE LTD.','','','','dsamaddar'
exec spInsertClientInfo 'T.H. PAPER & PACKAGING INDUSTRIES','','','','dsamaddar'
exec spInsertClientInfo 'A.M. POLY PACKAGING INDUSTRIES','','','','dsamaddar'
exec spInsertClientInfo 'XCLUSIVE CAN LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'M/S SHAH JALAL OIL MILLS','','','','dsamaddar'
exec spInsertClientInfo 'A.B.I.PACKAGES','','','','dsamaddar'
exec spInsertClientInfo 'I.S. METAL WORKS','','','','dsamaddar'
exec spInsertClientInfo 'M/S SALMA TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'S. A. PRINTING & PACKAGES CO.','','','','dsamaddar'
exec spInsertClientInfo 'BANGLADESH RURAL & AGRICULTURAL VENTURES LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'BENGAL PROTEIN AND FAT SUPPLIER CO','','','','dsamaddar'
exec spInsertClientInfo 'M/S AZIZ TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S MIZAN ENGINEERING WORKS','','','','dsamaddar'
exec spInsertClientInfo 'M/S S. S ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. HAJI CARRIERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SHAFIK ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'SHANIMA POLY & PACKAGING INDUSTRIES LIMITED.','','','','dsamaddar'
exec spInsertClientInfo 'TANJIM PRINTING & PACKAGING LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'AL HABIB ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. NASRIN TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'MASTER PACKAGING','','','','dsamaddar'
exec spInsertClientInfo 'M/S. RAJ ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. TORIQUL ISLAM','','','','dsamaddar'
exec spInsertClientInfo 'M/S. BILLAL HOSSAIN','','','','dsamaddar'
exec spInsertClientInfo 'M/S. NOFOR TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'SIGNAGE','','','','dsamaddar'
exec spInsertClientInfo 'ARTSIGN PVT. LTD.','','','','dsamaddar'
exec spInsertClientInfo 'UNITY SERVICES LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'LEOS PLASTICS','','','','dsamaddar'
exec spInsertClientInfo 'NOBLE PRINTING & PACKAGING LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'MARKET ACCESS PROVIDERS LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'POLYCON LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'PEOPLE SCAPE LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'EON ANIMAL HEALTH PRODUCTS LTD.','','','','dsamaddar'
exec spInsertClientInfo 'FAMOUS ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'BANGLA FOILS LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'SHURWID INDUSTRIES LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'MARKET EXPRESS LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'THREE STAR CORPORATION','','','','dsamaddar'
exec spInsertClientInfo 'UNITY SERVICES LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'REMEX INGREDIENT SOLUTION','','','','dsamaddar'
exec spInsertClientInfo 'M.M INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'ARTSIGN PVT. LTD.','','','','dsamaddar'
exec spInsertClientInfo 'SALVO PLUS','','','','dsamaddar'
exec spInsertClientInfo 'RESTAURANT BATON ROUGE','','','','dsamaddar'
exec spInsertClientInfo 'ISLAM ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'INTERGRAPHIC LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'INTERPACK LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'MEEM INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'VESPER MULTI TRADE','','','','dsamaddar'
exec spInsertClientInfo 'MAM CORPORATION','','','','dsamaddar'
exec spInsertClientInfo 'SADIA INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'Q PAIL LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SUPER PACK','','','','dsamaddar'
exec spInsertClientInfo 'CHAPAI AGRO PRODUCT MARKETING COMPANY','','','','dsamaddar'
exec spInsertClientInfo 'BIOLAB','','','','dsamaddar'
exec spInsertClientInfo 'SKY TRACKER LTD.','','','','dsamaddar'
exec spInsertClientInfo 'GENUINE STATIONERS & GIFT CORNER','','','','dsamaddar'
exec spInsertClientInfo 'MILON TRADE FAIR','','','','dsamaddar'
exec spInsertClientInfo 'INTERGRAPHIC LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'MIMOS TRADE VISION','','','','dsamaddar'
exec spInsertClientInfo 'PROTIK DISTRIBUTION LTD','','','','dsamaddar'
exec spInsertClientInfo 'M/S RIFA ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. HAKS INDUSTRIES LTD.','','','','dsamaddar'
exec spInsertClientInfo 'M/S PITICON INDUSTRIES','','','','dsamaddar'
exec spInsertClientInfo 'INTERPACK LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'M/S. FOOD WORLD','','','','dsamaddar'
exec spInsertClientInfo 'COMPUTER SOURCE LTD.','','','','dsamaddar'
exec spInsertClientInfo 'DESH PACKAGING','','','','dsamaddar'
exec spInsertClientInfo 'SARKER STEEL LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'I R ACTIVATION & PROMOTION LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'ROTO SMART LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'SADIA INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'M/S. SHAKIL MOBAYECHH PARIBAHAN','','','','dsamaddar'
exec spInsertClientInfo 'FARJANA PACKAGING','','','','dsamaddar'
exec spInsertClientInfo 'M/S SAMRAT ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. MOHAMMAD ALI TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'AL AMIN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'J. S. R. INTERNATIONAL','','','','dsamaddar'
exec spInsertClientInfo 'M/S SHAROTHI ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. BISMILLAH TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'NABAB AUTO RICE & FEED MILLS (PVT.) LIMITED','','','','dsamaddar'
exec spInsertClientInfo 'M/S. AUSHES TRADERS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. LAMIA AGRO','','','','dsamaddar'
exec spInsertClientInfo 'M/S. A.R. TRADING','','','','dsamaddar'
exec spInsertClientInfo 'M/S. RARES ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'M/S. ABDUL AZIZ','','','','dsamaddar'
exec spInsertClientInfo 'K. B. AD.','','','','dsamaddar'
exec spInsertClientInfo 'SALVO PLUS','','','','dsamaddar'
exec spInsertClientInfo 'S. S. PACKAGING INDUSTRIES','','','','dsamaddar'
exec spInsertClientInfo 'MARS TRADING CORPORATION','','','','dsamaddar'
exec spInsertClientInfo 'BORENDRO PLASTIC INDUSTRIES','','','','dsamaddar'
exec spInsertClientInfo 'PAPER RHYME','','','','dsamaddar'
exec spInsertClientInfo 'DHAKA PRODUCTS','','','','dsamaddar'
exec spInsertClientInfo 'M/S. HADIUZZAMAN ENTERPRISE','','','','dsamaddar'
exec spInsertClientInfo 'DURANTO AGRO INDUSTRIES','','','','dsamaddar'

*/